#+TITLE: My customised dwm
#+SUBTITLE: Original =README= edited to account for my customisations.

* Organisation

- Any patch for =config.def.h= must be propagated to =config.h=.

* Original README

dwm is an extremely fast, small, and dynamic window manager for X.

** Requirements

In order to build dwm you need the =Xlib= header files.

** Installation

Edit =config.mk= to match your local setup (dwm is installed into the =/usr/local=
namespace by default).

Afterwards enter the following command to build and install dwm (if necessary
as root):

#+BEGIN_SRC bash
make clean install
#+END_SRC

** Running dwm

Add the following line to your =.xinitrc= to start dwm using startx:

#+BEGIN_SRC bash
exec dwm
#+END_SRC

In order to connect dwm to a specific display, make sure that the =DISPLAY=
environment variable is set correctly, e.g.:

#+BEGIN_SRC bash
DISPLAY=foo.bar:1 exec dwm
#+END_SRC

(This will start dwm on display :1 of the host foo.bar.)

In order to display status info in the bar, you can do something like this in
your =.xinitrc=:

#+BEGIN_SRC bash
  while xsetroot -name "`date` `uptime | sed 's/.*,//'`" do sleep 1 done & exec
  dwm
#+END_SRC

** Configuration

The configuration of dwm is done by creating a custom =config.h= and
(re)compiling the source code.
